# Generated by Django 2.1.7 on 2019-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190228_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQOauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('openid', models.CharField(default='', max_length=50, verbose_name='认证码')),
            ],
            options={
                'verbose_name': 'QQ登录',
                'verbose_name_plural': 'QQ登录',
            },
        ),
        migrations.CreateModel(
            name='WeiboOauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('uid', models.CharField(default='', max_length=50, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '微博登录',
                'verbose_name_plural': '微博登录',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oauthtoken',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份id'),
        ),
    ]
