# Generated by Django 2.1.7 on 2019-03-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190324_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QQOauth',
        ),
        migrations.DeleteModel(
            name='WeiboOauth',
        ),
    ]
