# Generated by Django 2.1.7 on 2019-08-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190811_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='origin',
        ),
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
