# Generated by Django 2.1.7 on 2019-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=0, max_length=1, verbose_name='性别'),
        ),
    ]
