# Generated by Django 2.1.7 on 2019-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191116_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱'),
        ),
    ]
