# Generated by Django 2.1.7 on 2019-12-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191214_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '短信验证码', 'verbose_name_plural': '短信验证码'},
        ),
    ]
