# Generated by Django 2.1.7 on 2020-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=20, verbose_name='IP')),
                ('addr', models.CharField(default='', max_length=20, verbose_name='定位')),
                ('isp_name', models.CharField(default='', max_length=20, verbose_name='运营商')),
                ('path', models.CharField(default='', max_length=20, verbose_name='访问路径')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '访客IP',
                'verbose_name_plural': '访客IP',
            },
        ),
    ]
