# Generated by Django 3.0.6 on 2020-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=20, verbose_name='IP')),
                ('addr', models.CharField(default='', max_length=20, verbose_name='国家')),
                ('path', models.TextField(default='', verbose_name='访问路径')),
                ('user_agent', models.TextField(default='', verbose_name='请求头')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '访客信息',
                'verbose_name_plural': '访客信息',
            },
        ),
    ]
