# Generated by Django 2.1.7 on 2020-03-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plantform',
            field=models.CharField(default='', max_length=10, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='client',
            name='addr',
            field=models.CharField(default='', max_length=20, verbose_name='地区'),
        ),
    ]
