# Generated by Django 2.1.7 on 2020-03-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200303_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '访客信息', 'verbose_name_plural': '访客信息'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='addr',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='isp_name',
            new_name='isp',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plantform',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='', max_length=20, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='client',
            name='res_status',
            field=models.IntegerField(default=200, max_length=3, verbose_name='响应状态'),
        ),
        migrations.AddField(
            model_name='client',
            name='ua',
            field=models.TextField(default='', verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='client',
            name='path',
            field=models.TextField(default='', verbose_name='访问路径'),
        ),
    ]
