# Generated by Django 2.1.7 on 2020-03-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200324_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='res_status',
            field=models.IntegerField(default=200, verbose_name='响应状态'),
        ),
    ]
