# Generated by Django 2.1.7 on 2020-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follows', models.CharField(default='', max_length=10, verbose_name='关注数')),
                ('fans', models.CharField(default='', max_length=10, verbose_name='粉丝数')),
                ('likes', models.CharField(default='', max_length=10, verbose_name='总点赞数')),
                ('plays', models.CharField(default='', max_length=10, verbose_name='总播放量')),
                ('add_time', models.CharField(default='', max_length=15, verbose_name='记录日期')),
            ],
            options={
                'verbose_name': '统计',
                'verbose_name_plural': '统计',
            },
        ),
        migrations.CreateModel(
            name='Videolist',
            fields=[
                ('aid', models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='视频id')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('play', models.CharField(default='', max_length=8, verbose_name='播放量')),
                ('likes', models.CharField(default='', max_length=8, verbose_name='点赞数')),
                ('reply', models.CharField(default='', max_length=8, verbose_name='评论数')),
                ('danmaku', models.CharField(default='', max_length=8, verbose_name='弹幕数')),
                ('favorite', models.CharField(default='', max_length=8, verbose_name='收藏数')),
                ('coin', models.CharField(default='', max_length=8, verbose_name='硬币数')),
                ('share', models.CharField(default='', max_length=8, verbose_name='分享数')),
                ('pubtime', models.CharField(default='', max_length=15, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
            },
        ),
    ]
