# Generated by Django 2.1.7 on 2020-02-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolist',
            old_name='likes',
            new_name='like',
        ),
    ]
