# Generated by Django 2.1.7 on 2020-02-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0002_auto_20200210_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolist',
            old_name='like',
            new_name='like_count',
        ),
    ]
