# Generated by Django 2.1.7 on 2020-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0003_auto_20200210_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='add_time',
            field=models.CharField(default='', max_length=20, verbose_name='记录日期'),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='pubtime',
            field=models.CharField(default='', max_length=20, verbose_name='发布时间'),
        ),
    ]
