# Generated by Django 2.1.7 on 2020-03-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0007_remove_videolist_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '基础信息', 'verbose_name_plural': '基础信息'},
        ),
        migrations.AlterModelOptions(
            name='videolist',
            options={'verbose_name': '视频列表', 'verbose_name_plural': '视频列表'},
        ),
        migrations.AddField(
            model_name='videolist',
            name='add_time',
            field=models.CharField(default='', max_length=20, verbose_name='查询日期'),
        ),
    ]
