# Generated by Django 2.1.7 on 2019-02-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type_name',
        ),
    ]
