# Generated by Django 2.1.7 on 2019-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type_name',
            field=models.CharField(default='drf', max_length=10),
        ),
    ]
