# Generated by Django 2.1.7 on 2019-02-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article_type', verbose_name='分类'),
        ),
    ]
