# Generated by Django 2.1.7 on 2019-02-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190227_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='article.Article_type', verbose_name='分类'),
        ),
    ]
