# Generated by Django 2.1.7 on 2019-02-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190227_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='article',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
