# Generated by Django 2.1.7 on 2019-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190512_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaupload',
            name='fileurl',
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='imageurl',
            field=models.ImageField(default='', upload_to='content/'),
            preserve_default=False,
        ),
    ]
