# Generated by Django 2.1.7 on 2019-05-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20190512_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaupload',
            old_name='imageurl',
            new_name='upload',
        ),
    ]
