# Generated by Django 2.1.7 on 2019-05-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20190512_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fav_num',
        ),
    ]
