# Generated by Django 2.1.7 on 2019-07-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20190515_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaUpload',
        ),
    ]
