# Generated by Django 2.1.7 on 2019-08-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_delete_mediaupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='type_name',
        ),
        migrations.AddField(
            model_name='articletype',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='分类名字'),
            preserve_default=False,
        ),
    ]
