# Generated by Django 2.1.7 on 2019-08-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20190810_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType', verbose_name='文章分类'),
        ),
    ]
