# Generated by Django 2.1.7 on 2019-12-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20191116_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='click_num',
        ),
    ]
