# Generated by Django 2.1.7 on 2019-12-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_remove_article_click_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type_name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(default='', verbose_name='概述'),
        ),
    ]
