# Generated by Django 2.1.7 on 2019-12-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Photo',
        ),
    ]
