# Generated by Django 2.1.7 on 2019-09-22 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinghua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jinghua',
            name='otime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间'),
        ),
    ]
