# Generated by Django 2.1.7 on 2019-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinghua', '0002_auto_20190922_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jinghua',
            name='otime',
            field=models.DateTimeField(default=None, verbose_name='操作时间'),
        ),
    ]
