# Generated by Django 2.1.7 on 2019-12-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jinghua', '0004_auto_20190922_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jinghua',
            options={'verbose_name': '词条净化', 'verbose_name_plural': '词条净化'},
        ),
    ]
