# Generated by Django 2.1.7 on 2019-08-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jinyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otype', models.CharField(default='1', max_length=10, verbose_name='操作者类型')),
                ('snic', models.CharField(default='', max_length=50, verbose_name='操作者昵称')),
                ('dnic', models.CharField(default='', max_length=50, verbose_name='被禁言昵称')),
                ('endtime', models.CharField(default='', max_length=20, verbose_name='禁言结束时间')),
            ],
            options={
                'verbose_name': '禁言',
                'verbose_name_plural': '禁言',
            },
        ),
    ]
