# Generated by Django 2.1.7 on 2019-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmu', '0002_jinyan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liwu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('gfid', models.CharField(default='', max_length=10, verbose_name='礼物id')),
                ('gfcnt', models.CharField(default='1', max_length=10, verbose_name='礼物数量')),
                ('hits', models.CharField(default='1', max_length=10, verbose_name='连击数')),
            ],
            options={
                'verbose_name': '礼物',
                'verbose_name_plural': '礼物',
            },
        ),
    ]
