# Generated by Django 2.1.7 on 2019-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmu', '0003_liwu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danmu',
            name='sendtime',
            field=models.DateTimeField(default=None, max_length=20, verbose_name='发送时间'),
        ),
    ]
