# Generated by Django 2.1.7 on 2019-09-22 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmu', '0005_auto_20190922_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danmu',
            name='sendtime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
    ]
