# Generated by Django 2.1.7 on 2019-10-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danmu', '0006_auto_20190922_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liwu',
        ),
    ]
